# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
install:
  - Rscript -e 'install.packages(c("devtools","testthat"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("knitr","rmarkdown"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("DiceKriging", "DiceOptim", "GenSA", "emoa", "mco", "GPareto", "methods", "lhs"), repos = "http://cran.rstudio.com")'
